# Dokapi_url is deprecated. Please use folio.client.okapiUrl instead
Dokapi_url: http://localhost:9130
# okapi_url is deprecated. Please use folio.client.okapiUrl instead
okapi_url: ${Dokapi_url}
Dsecure_store_props: src/main/resources/ephemeral.properties
secure_store_props: ${Dsecure_store_props}
Dsecure_store: Ephemeral
secure_store: ${Dsecure_store}
Dcaia_soft_client: caiaSoftClient
caia_soft_client: ${Dcaia_soft_client}
Dcaia_soft_tenants: caiaSoftClient_tenants
caia_soft_tenants: ${Dcaia_soft_tenants}
spring:
  application:
    name: edge-caiasoft
  jackson:
    default-property-inclusion: non_null
  liquibase:
    enabled: false
  flyway:
    enabled: false
  cloud:
    openfeign:
      okhttp:
        enabled: true
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health,info,loggers
  endpoint:
    loggers:
      enabled: true
feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    org:
      springframework:
        cache: OFF
server.port: 8081
folio:
  tenant:
  validation:
    enabled: false
  system-user:
    username: ${SYSTEM_USER_NAME:system-user}
    password: ${SYSTEM_USER_PASSWORD}
  environment: ${ENV:folio}
  okapi-url: ${Dokapi_url:http://okapi:9130}
  client:
    okapiUrl: http://localhost:9130
    tls:
      enabled: false
#      trustStorePath: ~/test/test.truststore.bcfks
#      trustStorePassword: "SecretPassword"
#      trustStoreType: BCFKS

# configurations update timeframe (millis)
configurations.update.timeframe: 3600000
